# Generated by Django 4.0.3 on 2023-05-17 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_word_delete_answer_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.word')),
            ],
        ),
    ]
